// <auto-generated />
using Labb3API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb3API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220915114143_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InterestDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("InterestTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            InterestDescription = "Loves to run around the lake house after submerged from the lake and scare and slaughter teenagers",
                            InterestTitle = "Lake houses"
                        },
                        new
                        {
                            InterestId = 2,
                            InterestDescription = "Hunt people at halloween",
                            InterestTitle = "Halloween"
                        },
                        new
                        {
                            InterestId = 3,
                            InterestDescription = "To roam in peoples dreams and take them out",
                            InterestTitle = "Dreams"
                        },
                        new
                        {
                            InterestId = 4,
                            InterestDescription = "Likes to cook meat, but not animal meat as the rest of us eats",
                            InterestTitle = "To eat"
                        },
                        new
                        {
                            InterestId = 5,
                            InterestDescription = "Big machetetes is a favorite",
                            InterestTitle = "Machetes"
                        },
                        new
                        {
                            InterestId = 6,
                            InterestDescription = "Old school hockey masks, used to cover a rotten face from a drowning",
                            InterestTitle = "Hockey masks"
                        },
                        new
                        {
                            InterestId = 7,
                            InterestDescription = "Loves to make custom gloves.. especially with razor sharp knives on the fingers",
                            InterestTitle = "Custom gloves"
                        },
                        new
                        {
                            InterestId = 8,
                            InterestDescription = "Just like Jason Voorhees, Michael likes to wear a mask over his face, but not an old hockey mask.. but both wear white masks",
                            InterestTitle = "Halloween mask"
                        },
                        new
                        {
                            InterestId = 9,
                            InterestDescription = "Loves to run around the lake house after submerged from the lake and scare and slaughter teenagers",
                            InterestTitle = "Lake houses"
                        });
                });

            modelBuilder.Entity("Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("LinkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("LinkId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            InterestId = 1,
                            LinkDescription = "A clip of Jason in action",
                            LinkUrl = "https://www.youtube.com/watch?v=yfxQmKO041o",
                            PersonId = 1
                        },
                        new
                        {
                            LinkId = 2,
                            InterestId = 2,
                            LinkDescription = "A clip of Michael doing what he does at halloween night",
                            LinkUrl = "https://www.youtube.com/watch?v=R-HV-gTRqag",
                            PersonId = 2
                        },
                        new
                        {
                            LinkId = 3,
                            InterestId = 3,
                            LinkDescription = "Freddie does his thing",
                            LinkUrl = "https://www.youtube.com/watch?v=HcrTqof683A",
                            PersonId = 3
                        },
                        new
                        {
                            LinkId = 4,
                            InterestId = 4,
                            LinkDescription = "Hannibal in prison",
                            LinkUrl = "https://www.youtube.com/watch?v=s3nIw30hn4U",
                            PersonId = 4
                        },
                        new
                        {
                            LinkId = 5,
                            InterestId = 7,
                            LinkDescription = "A clip of Freddie making gloves",
                            LinkUrl = "https://www.youtube.com/watch?v=FnEmVboDO0Q",
                            PersonId = 3
                        },
                        new
                        {
                            LinkId = 6,
                            InterestId = 5,
                            LinkDescription = "Jason shows off his Machete",
                            LinkUrl = "https://www.youtube.com/watch?v=p2ff-fiJAcs",
                            PersonId = 1
                        },
                        new
                        {
                            LinkId = 7,
                            InterestId = 8,
                            LinkDescription = "Michael Myers got his mask taken off",
                            LinkUrl = "https://www.youtube.com/watch?v=9dQ5Q7ILApE",
                            PersonId = 2
                        },
                        new
                        {
                            LinkId = 8,
                            InterestId = 6,
                            LinkDescription = "Jason Voorhees with his mask",
                            LinkUrl = "https://www.youtube.com/watch?v=CflcJ-HSA_Y",
                            PersonId = 1
                        });
                });

            modelBuilder.Entity("Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Email = "jason.voorhees@friday13th.com",
                            FirstName = "Jason",
                            LastName = "Voorhees",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            PersonId = 2,
                            Email = "michael.myers@halloween.com",
                            FirstName = "Michael",
                            LastName = "Myers",
                            Phone = "555-123-4657"
                        },
                        new
                        {
                            PersonId = 3,
                            Email = "freddie.krueger@terroronelmstreet.com",
                            FirstName = "Freddie",
                            LastName = "Krueger",
                            Phone = "555-123-7564"
                        },
                        new
                        {
                            PersonId = 4,
                            Email = "hannibal.lecter@thesilenceofthelambs.com",
                            FirstName = "Hannibal",
                            LastName = "Lecter",
                            Phone = "555-123-5476"
                        });
                });

            modelBuilder.Entity("Models.PersonInterest", b =>
                {
                    b.Property<int>("PersonInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonInterestId = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 2,
                            InterestId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            PersonInterestId = 3,
                            InterestId = 3,
                            PersonId = 3
                        },
                        new
                        {
                            PersonInterestId = 4,
                            InterestId = 4,
                            PersonId = 4
                        },
                        new
                        {
                            PersonInterestId = 5,
                            InterestId = 5,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 6,
                            InterestId = 6,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 7,
                            InterestId = 7,
                            PersonId = 3
                        },
                        new
                        {
                            PersonInterestId = 8,
                            InterestId = 8,
                            PersonId = 2
                        });
                });

            modelBuilder.Entity("Models.Link", b =>
                {
                    b.HasOne("Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.PersonInterest", b =>
                {
                    b.HasOne("Models.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
